Set-StrictMode -Version 2.0

$script:CollectorVersion = "4.3.0"
$script:SchemaVersion = "4.3"
$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Get-CollectorConfigValue {
    param(
        [Parameter(Mandatory=$true)][hashtable]$Config,
        [Parameter(Mandatory=$true)][string]$Name,
        [string]$LegacyName = "",
        [AllowNull()][object]$DefaultValue = $null
    )
    if ($Config.ContainsKey($Name)) { return $Config[$Name] }
    if ($LegacyName -and $Config.ContainsKey($LegacyName)) { return $Config[$LegacyName] }
    return $DefaultValue
}

function ConvertTo-CollectorSwitch {
    param(
        [AllowNull()][object]$Value,
        [Parameter(Mandatory=$true)][string]$Name
    )
    if ($Value -is [bool]) { return [bool]$Value }
    switch (([string]$Value).Trim().ToLowerInvariant()) {
        "on" { return $true }
        "off" { return $false }
        default { throw "$Name 只能设置为 on 或 off" }
    }
}

function ConvertTo-CollectorConfig {
    param([Parameter(Mandatory=$true)][hashtable]$Config)

    if ($Config.ContainsKey("DB_INTERACTIVE_LOGIN")) {
        $interactive = ConvertTo-CollectorSwitch $Config.DB_INTERACTIVE_LOGIN "DB_INTERACTIVE_LOGIN"
    } elseif ($Config.ContainsKey("AuthMode")) {
        $interactive = ([string]$Config.AuthMode).Trim() -ieq "Interactive"
    } else {
        $interactive = $false
    }
    $walletAlias = [string](Get-CollectorConfigValue $Config "DB_WALLET_ALIAS" "WalletAlias" "")
    $authMode = if ($interactive) { "Interactive" } elseif ($walletAlias) { "Wallet" } else { "OS" }

    return @{
        OracleSid = [string](Get-CollectorConfigValue $Config "ORACLE_SID" "OracleSid" "")
        OracleHome = [string](Get-CollectorConfigValue $Config "ORACLE_HOME" "OracleHome" "")
        AuthMode = $authMode
        WalletAlias = $walletAlias
        CheckHost = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "CHECK_HOST" "CheckHost" $true) "CHECK_HOST"
        CheckDatabase = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "CHECK_DB" "CheckDatabase" $true) "CHECK_DB"
        CheckSecurity = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "CHECK_SECURITY" "CheckSecurity" $true) "CHECK_SECURITY"
        CheckAwr = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "CHECK_AWR" "CheckAwr" $false) "CHECK_AWR"
        CollectSqlText = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "COLLECT_SQL_TEXT" "CollectSqlText" $false) "COLLECT_SQL_TEXT"
        RawDataDir = [string](Get-CollectorConfigValue $Config "RAW_DATA_DIR" "RawDataDir" "output\raw")
        Debug = ConvertTo-CollectorSwitch (Get-CollectorConfigValue $Config "DEBUG" "Debug" $false) "DEBUG"
        ReportFooter = [string](Get-CollectorConfigValue $Config "REPORT_FOOTER" "ReportFooter" "Generated by OraSentry")
    }
}

function Write-CollectorText {
    param([Parameter(Mandatory=$true)][string]$Path, [AllowEmptyString()][string]$Text)
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    [System.IO.File]::WriteAllText($Path, $Text, $script:Utf8NoBom)
}

function Write-CollectorLines {
    param([Parameter(Mandatory=$true)][string]$Path, [object[]]$Lines)
    $text = if ($Lines) { ($Lines | ForEach-Object { [string]$_ }) -join "`r`n" } else { "" }
    if ($text) { $text += "`r`n" }
    Write-CollectorText -Path $Path -Text $text
}

function ConvertTo-SafeField {
    param([AllowNull()][object]$Value)
    if ($null -eq $Value) { return "" }
    return ([string]$Value).Replace("|", "/").Replace("`t", " ").Replace("`r", " ").Replace("`n", " ")
}

function Write-PipeTable {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string[]]$Headers,
        [object[]]$Rows
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add((($Headers | ForEach-Object { ConvertTo-SafeField $_ }) -join "|"))
    foreach ($row in @($Rows)) {
        if ($null -eq $row) { continue }
        $values = if ($row -is [System.Array]) { $row } else { @($row) }
        $lines.Add((($values | ForEach-Object { ConvertTo-SafeField $_ }) -join "|"))
    }
    Write-CollectorLines -Path $Path -Lines $lines
}

function Write-CollectorLog {
    param(
        [Parameter(Mandatory=$true)]$Context,
        [ValidateSet("INFO","WARN","ERROR")][string]$Level = "INFO",
        [Parameter(Mandatory=$true)][string]$Message
    )
    $line = "[{0}] [{1}] {2}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Level, $Message
    Write-Host $line
    [System.IO.File]::AppendAllText($Context.LogFile, $line + "`r`n", $script:Utf8NoBom)
}

function Write-CollectorErrorRecord {
    param(
        [Parameter(Mandatory=$true)]$Context,
        [Parameter(Mandatory=$true)][System.Management.Automation.ErrorRecord]$ErrorRecord,
        [string]$Prefix = ""
    )
    Write-CollectorLog -Context $Context -Level "ERROR" -Message ($Prefix + $ErrorRecord.Exception.Message)
    $invocation = $ErrorRecord.InvocationInfo
    if ($invocation) {
        $scriptName = if ($invocation.ScriptName) { $invocation.ScriptName } else { "<interactive>" }
        $commandName = if ($invocation.MyCommand -and $invocation.MyCommand.Name) { $invocation.MyCommand.Name } else { "<unknown>" }
        Write-CollectorLog -Context $Context -Level "ERROR" -Message (
            "错误位置: {0}:{1}:{2}; command={3}" -f $scriptName, $invocation.ScriptLineNumber, $invocation.OffsetInLine, $commandName
        )
    }
    if ($ErrorRecord.FullyQualifiedErrorId -or $ErrorRecord.CategoryInfo) {
        Write-CollectorLog -Context $Context -Level "ERROR" -Message (
            "错误标识: {0}; category={1}" -f $ErrorRecord.FullyQualifiedErrorId, $ErrorRecord.CategoryInfo
        )
    }
    if ($ErrorRecord.ScriptStackTrace) {
        $stack = ($ErrorRecord.ScriptStackTrace -replace "`r?`n", " <- ").Trim()
        Write-CollectorLog -Context $Context -Level "ERROR" -Message "调用栈: $stack"
    }
}

function Add-CollectionManifest {
    param(
        [Parameter(Mandatory=$true)]$Context,
        [Parameter(Mandatory=$true)][string]$Item,
        [Parameter(Mandatory=$true)][string]$Type,
        [Parameter(Mandatory=$true)][ValidateSet("OK","WARN","FAILED","SKIPPED")][string]$Status,
        [int]$ExitCode = 0,
        [string]$Message = ""
    )
    $safeMessage = ConvertTo-SafeField $Message
    $line = "{0}`t{1}`t{2}`t{3}`t{4}`r`n" -f (ConvertTo-SafeField $Item), $Type, $Status, $ExitCode, $safeMessage
    [System.IO.File]::AppendAllText($Context.ManifestFile, $line, $script:Utf8NoBom)
    if ($Status -eq "FAILED") { $Context.Failures++ }
    if ($Status -eq "WARN") { $Context.Warnings++ }
}

function Invoke-CollectionAction {
    param(
        [Parameter(Mandatory=$true)]$Context,
        [Parameter(Mandatory=$true)][string]$Item,
        [Parameter(Mandatory=$true)][scriptblock]$Action,
        [string]$Type = "COMMAND",
        [switch]$Optional
    )
    try {
        & $Action | Out-Null
        Add-CollectionManifest -Context $Context -Item $Item -Type $Type -Status "OK"
        return
    } catch {
        $message = $_.Exception.Message
        if ($Optional) {
            Write-CollectorLog -Context $Context -Level "WARN" -Message "$Item 不可用: $message"
            Add-CollectionManifest -Context $Context -Item $Item -Type $Type -Status "WARN" -ExitCode 1 -Message $message
            return
        }
        Write-CollectorErrorRecord -Context $Context -ErrorRecord $_ -Prefix "$Item 采集失败: "
        Add-CollectionManifest -Context $Context -Item $Item -Type $Type -Status "FAILED" -ExitCode 1 -Message $message
        return
    }
}

function Get-PrimaryIPv4 {
    try {
        $address = Get-CimInstance Win32_NetworkAdapterConfiguration -ErrorAction Stop |
            Where-Object { $_.IPEnabled -and $_.IPAddress } |
            ForEach-Object { $_.IPAddress } |
            Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' -and $_ -notmatch '^169\.254\.' } |
            Select-Object -First 1
        if ($address) { return [string]$address }
    } catch {}
    return "N/A"
}

function Initialize-Collection {
    param(
        [Parameter(Mandatory=$true)][ValidateSet("host","db")][string]$CheckType,
        [Parameter(Mandatory=$true)][hashtable]$Config,
        [string]$OracleSid = ""
    )
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $collectorRoot = Split-Path -Parent $PSScriptRoot
    $rawSetting = [string]$Config.RawDataDir
    if ([System.IO.Path]::IsPathRooted($rawSetting)) {
        $rawBase = [System.IO.Path]::GetFullPath($rawSetting)
    } else {
        $rawBase = [System.IO.Path]::GetFullPath((Join-Path $collectorRoot $rawSetting))
    }
    New-Item -ItemType Directory -Force -Path $rawBase | Out-Null
    $rawDir = Join-Path $rawBase $timestamp
    if (Test-Path -LiteralPath $rawDir) {
        $timestamp = "{0}_{1}" -f $timestamp, $PID
        $rawDir = Join-Path $rawBase $timestamp
    }
    New-Item -ItemType Directory -Force -Path $rawDir | Out-Null

    $context = [pscustomobject]@{
        CheckType = $CheckType
        Timestamp = $timestamp
        CollectorRoot = $collectorRoot
        RawBase = $rawBase
        RawDir = $rawDir
        LogFile = Join-Path $rawDir "collect.log"
        ManifestFile = Join-Path $rawDir "collection_manifest.tsv"
        Failures = 0
        Warnings = 0
        OracleSid = $OracleSid
        OracleHome = ""
        AuthMode = ""
        SqlPlus = ""
        SecurePassword = $null
        LoginUser = ""
        ConnectDescriptor = ""
        LoginRole = "SYSDBA"
        PackageFile = ""
    }
    Write-CollectorText -Path $context.LogFile -Text ""
    Write-CollectorText -Path $context.ManifestFile -Text "item`ttype`tstatus`texit_code`tmessage`r`n"

    $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
    $osCaption = if ($os) { "{0} {1}" -f $os.Caption, $os.Version } else { [Environment]::OSVersion.VersionString }
    $envLines = @(
        "schema_version=$script:SchemaVersion",
        "collector_version=$script:CollectorVersion",
        "data_classification=confidential",
        "platform=windows",
        "platform_family=windows",
        "hostname=$env:COMPUTERNAME",
        "server_ip=$(Get-PrimaryIPv4)",
        "os=$osCaption",
        "kernel=$([Environment]::OSVersion.Version)",
        "powershell_version=$($PSVersionTable.PSVersion)",
        "timestamp=$timestamp",
        "check_type=$CheckType",
        "debug=$($Config.Debug)",
        "report_footer=$($Config.ReportFooter)"
    )
    if ($OracleSid) { $envLines += "oracle_sid=$OracleSid" }
    Write-CollectorLines -Path (Join-Path $rawDir "env.info") -Lines $envLines
    Write-CollectorLog -Context $context -Message "初始化 Windows $CheckType 采集目录: $rawDir"
    return $context
}

function Add-EnvironmentInfo {
    param([Parameter(Mandatory=$true)]$Context, [Parameter(Mandatory=$true)][string[]]$Lines)
    $path = Join-Path $Context.RawDir "env.info"
    $text = ($Lines -join "`r`n") + "`r`n"
    [System.IO.File]::AppendAllText($path, $text, $script:Utf8NoBom)
}

function Complete-Collection {
    param([Parameter(Mandatory=$true)]$Context)
    Add-EnvironmentInfo -Context $Context -Lines @(
        "collection_failures=$($Context.Failures)",
        "collection_warnings=$($Context.Warnings)",
        "collection_completed_at=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
    )
    if ($Context.Failures -gt 0) {
        Write-CollectorLog -Context $Context -Level "ERROR" -Message "采集存在 $($Context.Failures) 个失败项，详见 collection_manifest.tsv"
        return $false
    }
    Write-CollectorLog -Context $Context -Message "采集完整性校验通过"
    return $true
}
