# -*- coding: utf-8 -*-
"""
巡检阈值配置 - Python 端
所有阈值判定逻辑在 Python 端执行，与 Shell 采集端完全分离
"""

# 主机巡检阈值
HOST_THRESHOLDS = {
    "disk_usage_warn": 80,       # 磁盘使用率警告(%)
    "disk_usage_crit": 90,       # 磁盘使用率严重(%)
    "disk_free_warn": 10,        # 磁盘可用空间警告(GB)
    "disk_free_crit": 5,         # 磁盘可用空间严重(GB)
    "cpu_usage_warn": 80,        # CPU使用率警告(%)
    "cpu_usage_crit": 95,        # CPU使用率严重(%)
    "mem_usage_warn": 80,        # 内存使用率警告(%)
    "mem_usage_crit": 95,        # 内存使用率严重(%)
    "swap_usage_warn": 50,      # Swap占用率警告(%)，需结合实时换页活动判断
    "swap_usage_crit": 80,      # Swap占用率严重(%)
    "inode_usage_warn": 80,
    "inode_usage_crit": 90,
    "load_per_cpu_warn": 1.0,
    "load_per_cpu_crit": 2.0,
    "iowait_warn": 10,
    "iowait_crit": 25,
    "disk_await_warn_ms": 20,
    "disk_await_crit_ms": 50,
    "disk_util_warn": 70,
    "disk_util_crit": 90,
}

# 数据库巡检阈值
DB_THRESHOLDS = {
    "tablespace_usage_warn": 85,    # 表空间使用率警告(%)
    "tablespace_usage_crit": 95,    # 表空间使用率严重(%)
    "buffer_hit_ratio_warn": 90,    # 缓冲区命中率警告(低于此值)
    "buffer_hit_ratio_crit": 80,    # 缓冲区命中率严重(低于此值)
    "library_hit_ratio_warn": 95,   # 共享池命中率警告(低于此值)
    "library_hit_ratio_crit": 90,   # 共享池命中率严重(低于此值)
    "session_usage_warn": 80,       # 会话使用率警告(%)
    "session_usage_crit": 90,       # 会话使用率严重(%)
    "asm_usage_warn": 85,           # ASM使用率警告(%)
    "asm_usage_crit": 95,           # ASM使用率严重(%)
    "archive_usage_warn": 80,       # 归档日志使用率警告(%)
    "archive_usage_crit": 90,       # 归档日志使用率严重(%)
    "frag_table_count_warn": 5,     # 高碎片表数量警告
    "frag_table_count_crit": 10,    # 高碎片表数量严重
    "dead_session_count_warn": 10,  # 僵死会话数量警告
    "dead_session_count_crit": 50,  # 僵死会话数量严重
    "alert_error_count_warn": 5,    # alert log错误数警告
    "alert_error_count_crit": 20,   # alert log错误数严重
    "resource_usage_warn": 80,
    "resource_usage_crit": 90,
    "blocking_session_warn": 1,
    "blocking_session_crit": 5,
    "stale_stats_warn": 20,
    "stale_stats_crit": 100,
}

# 健康评分采用归一化加权模型。权重只表达业务影响，状态严重度由
# OK/WARN/CRIT 独立表达；未列出的检查项使用默认权重。
DEFAULT_SCORE_WEIGHT = 1
CHECK_SCORE_WEIGHTS = {
    # 数据库核心可用性、恢复能力与数据完整性
    "实例状态": 5,
    "数据库组件状态": 5,
    "数据文件恢复与坏块": 5,
    "Data Guard/归档传输": 5,
    "备份状态": 5,
    "归档日志使用率": 5,
    "控制文件": 5,
    "数据文件": 5,
    "表空间使用概览": 5,
    "CDB/PDB": 5,
    "RAC集群": 5,
    "RAC服务": 5,
    "监听器与SQL*Net安全": 5,

    # 重要配置、容量、性能与安全基线
    "数据库补丁": 3,
    "数据库韧性配置": 3,
    "Redo Log": 3,
    "ASM磁盘组": 3,
    "会话与进程": 3,
    "数据库资源上限": 3,
    "阻塞会话": 3,
    "缓冲区命中率": 3,
    "共享池命中率": 3,
    "Alert Log": 3,
    "密码过期策略": 3,
    "数据库安全性": 3,
    "数据库审计": 3,
    "PUBLIC高风险授权": 3,
    "系统权限最小化": 3,
    "安全参数": 3,
    "操作系统安全性": 3,
    "磁盘使用概览": 3,
    "inode使用率": 3,
    "CPU使用率": 3,
    "内存使用率": 3,
    "Swap使用率": 3,
    "防火墙状态": 3,
    "内核参数": 3,
    "时间同步": 3,
    "网络监听端口": 3,
    "系统日志": 3,
    "Oracle HugePages": 3,
    "Transparent HugePages": 3,
    "磁盘IO延迟": 3,
}

# 动态检查项名称（例如“磁盘使用率-/data”）按前缀匹配。
CHECK_SCORE_PREFIX_WEIGHTS = {
    "磁盘使用率-": 5,
}

# 安全巡检阈值
SECURITY_THRESHOLDS = {
    "password_life_unlimited_warn": True,   # 密码永不过期是否警告
    "default_account_open_warn": True,      # 默认账户开启是否警告
    "non_sys_dba_warn": True,               # 非SYS的DBA用户是否警告
    "listener_no_password_warn": True,      # 监听器无密码是否警告
    "oracle_bin_perm_expected": "6751",     # oracle二进制期望权限
}

# 巡检类别中文名
CATEGORY_NAMES = {
    "host": "主机巡检",
    "db": "数据库巡检",
    "cdb": "CDB/PDB管理",
    "rac": "RAC集群",
    "security": "安全巡检",
}

CATEGORY_ORDER = ["host", "db", "cdb", "rac", "security"]

# 报告显示配置
REPORT_CONFIG = {
    "brand": "Oracle Inspector",              # 左侧导航栏 Logo 文字
    "project_name": "ORACLE INSPECTION REPORT",  # 报告封面项目名称默认值
    "footer": "Generated by Oracle Inspector v4.2",  # 页面底部文字
    "title_db": "Oracle 数据库巡检报告",       # 数据库巡检报告标题
    "title_host": "主机操作系统巡检报告",      # 主机巡检报告标题
    "title_general": "系统巡检报告",          # 通用巡检报告标题
    "title_summary": "Oracle 巡检汇总摘要报告",  # 多份报告合并后的管理层摘要
}
