@{
    # 配置项名称与 collector-linux/conf/check.conf 保持一致。
    # 留空时依次从当前进程环境、Oracle 注册表和 OracleService 服务探测。
    ORACLE_SID = ""
    ORACLE_HOME = ""

    # on：运行时手动输入数据库地址、账号和隐藏密码。
    # off：DB_WALLET_ALIAS 非空时使用 Wallet，否则使用本机 OS 认证 / as sysdba。
    # 禁止在本文件中保存数据库账号或密码。
    DB_INTERACTIVE_LOGIN = "off"
    DB_WALLET_ALIAS = ""

    # 巡检项开关（on/off）。
    CHECK_HOST = "on"
    CHECK_DB = "on"
    CHECK_SECURITY = "on"

    # AWR/DBA_HIST 可能涉及额外 Oracle 授权，默认关闭。
    CHECK_AWR = "off"
    COLLECT_SQL_TEXT = "off"

    RAW_DATA_DIR = "output\raw"
    DEBUG = "off"
    REPORT_FOOTER = "Generated by OraSentry"
}
