@{
    # 留空时依次从当前进程环境、Oracle注册表和OracleService服务探测。
    OracleSid = ""
    OracleHome = ""

    # OS（默认，本机ORA_DBA）、Wallet 或 Interactive。
    # 禁止在本文件中保存数据库账号或密码。
    AuthMode = "OS"
    WalletAlias = ""

    CheckHost = $true
    CheckDatabase = $true
    CheckSecurity = $true

    # AWR/DBA_HIST 可能涉及额外Oracle授权，默认关闭。
    CheckAwr = $false
    CollectSqlText = $false

    RawDataDir = "output\raw"
    Debug = $false
    ReportFooter = "Generated by OraSentry"
}
